<?php

declare(strict_types=1);

namespace App\Application\Identity;

use RuntimeException;

// Author by Lab | zefry
final class FirstPartyIdentityEligibilityAdministrationViolation extends RuntimeException
{
    public const AUTHORIZATION_DENIED = 'IDENTITY_AUTHENTICATION_ELIGIBILITY_ADMIN_AUTHORIZATION_DENIED';
    public const PERSISTENCE_DISABLED = 'IDENTITY_AUTHENTICATION_ELIGIBILITY_ADMIN_PERSISTENCE_DISABLED';
    public const RUNTIME_DENIED = 'IDENTITY_AUTHENTICATION_ELIGIBILITY_ADMIN_RUNTIME_DENIED';
    public const INVALID_MUTATION = 'IDENTITY_AUTHENTICATION_ELIGIBILITY_ADMIN_INVALID_MUTATION';
    public const TARGET_IDENTITY_DENIED = 'IDENTITY_AUTHENTICATION_ELIGIBILITY_ADMIN_TARGET_DENIED';
    public const PROTECTED_TARGET = 'IDENTITY_AUTHENTICATION_ELIGIBILITY_ADMIN_PROTECTED_TARGET';
    public const MUTATION_CONFLICT = 'IDENTITY_AUTHENTICATION_ELIGIBILITY_ADMIN_MUTATION_CONFLICT';
    public const STORAGE_FAILURE = 'IDENTITY_AUTHENTICATION_ELIGIBILITY_ADMIN_STORAGE_FAILURE';
    public const TRANSACTION_FAILURE = 'IDENTITY_AUTHENTICATION_ELIGIBILITY_ADMIN_TRANSACTION_FAILURE';

    public function __construct(public readonly string $errorCode, string $message)
    {
        parent::__construct($message);
    }
}
