<?php

declare(strict_types=1);

namespace App\Application\Authorization;

use RuntimeException;

// Author by Lab | zefry
final class InitialTenantAdministratorProvisioningViolation extends RuntimeException
{
    public const AUTHORIZATION_DENIED = 'INITIAL_TENANT_ADMIN_PROVISIONING_AUTHORIZATION_DENIED';
    public const PERSISTENCE_DISABLED = 'INITIAL_TENANT_ADMIN_PROVISIONING_PERSISTENCE_DISABLED';
    public const RUNTIME_DENIED = 'INITIAL_TENANT_ADMIN_PROVISIONING_RUNTIME_DENIED';
    public const INVALID_PROVISIONING = 'INITIAL_TENANT_ADMIN_PROVISIONING_INVALID_ID';
    public const IDENTITY_MISMATCH = 'INITIAL_TENANT_ADMIN_PROVISIONING_IDENTITY_MISMATCH';
    public const TENANT_RELATIONSHIP_DENIED = 'INITIAL_TENANT_ADMIN_PROVISIONING_TENANT_RELATIONSHIP_DENIED';
    public const ALREADY_INITIALIZED = 'INITIAL_TENANT_ADMIN_PROVISIONING_ALREADY_INITIALIZED';
    public const PROVISIONING_CONFLICT = 'INITIAL_TENANT_ADMIN_PROVISIONING_CONFLICT';
    public const ROLE_STATE_CONFLICT = 'INITIAL_TENANT_ADMIN_PROVISIONING_ROLE_STATE_CONFLICT';
    public const STORAGE_FAILURE = 'INITIAL_TENANT_ADMIN_PROVISIONING_STORAGE_FAILURE';
    public const TRANSACTION_FAILURE = 'INITIAL_TENANT_ADMIN_PROVISIONING_TRANSACTION_FAILURE';

    public function __construct(public readonly string $errorCode, string $message)
    {
        parent::__construct($message);
    }
}
