<?php

declare(strict_types=1);

namespace App\Application\Authorization;

use RuntimeException;

// Author by Lab | zefry
final class ProtectedControlAdministratorLifecycleViolation extends RuntimeException
{
    public const AUTHORIZATION_DENIED = 'PROTECTED_CONTROL_ADMIN_LIFECYCLE_AUTHORIZATION_DENIED';
    public const PERSISTENCE_DISABLED = 'PROTECTED_CONTROL_ADMIN_LIFECYCLE_PERSISTENCE_DISABLED';
    public const RUNTIME_DENIED = 'PROTECTED_CONTROL_ADMIN_LIFECYCLE_RUNTIME_DENIED';
    public const INVALID_MUTATION = 'PROTECTED_CONTROL_ADMIN_LIFECYCLE_INVALID_MUTATION';
    public const TARGET_IDENTITY_MISMATCH = 'PROTECTED_CONTROL_ADMIN_LIFECYCLE_TARGET_IDENTITY_MISMATCH';
    public const TENANT_RELATIONSHIP_DENIED = 'PROTECTED_CONTROL_ADMIN_LIFECYCLE_TENANT_RELATIONSHIP_DENIED';
    public const MUTATION_CONFLICT = 'PROTECTED_CONTROL_ADMIN_LIFECYCLE_MUTATION_CONFLICT';
    public const PROTECTED_ROLE_STATE_CONFLICT = 'PROTECTED_CONTROL_ADMIN_LIFECYCLE_ROLE_STATE_CONFLICT';
    public const LAST_CONTROL_PRINCIPAL = 'PROTECTED_CONTROL_ADMIN_LIFECYCLE_LAST_CONTROL_PRINCIPAL';
    public const STORAGE_FAILURE = 'PROTECTED_CONTROL_ADMIN_LIFECYCLE_STORAGE_FAILURE';
    public const TRANSACTION_FAILURE = 'PROTECTED_CONTROL_ADMIN_LIFECYCLE_TRANSACTION_FAILURE';

    public function __construct(public readonly string $errorCode, string $message)
    {
        parent::__construct($message);
    }
}
