<?php
declare(strict_types=1);

// Author by Lab | zefry
function prodReqFail(string$c):never{throw new RuntimeException($c);}
function prodReqLoad(string$p):array{if(!is_file($p)||is_link($p))prodReqFail('input');$r=(string)file_get_contents($p);try{$v=json_decode($r,true,64,JSON_THROW_ON_ERROR);}catch(JsonException){prodReqFail('json');}if(!is_array($v)||array_is_list($v))prodReqFail('shape');return['v'=>$v,'raw'=>$r];}
function prodReqEq(mixed$a,mixed$e,string$c):void{if($a!==$e)prodReqFail($c);}
function prodReqCanonical(array$v):string{$w=function(array$x)use(&$w):array{if(array_is_list($x))return array_map(fn($y)=>is_array($y)?$w($y):$y,$x);ksort($x,SORT_STRING);foreach($x as$k=>$y)if(is_array($y))$x[$k]=$w($y);return$x;};return json_encode($w($v),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);}
function prodReqPrepare(string$mp,string$ap,string$sp,string$tp):array{
 $m=prodReqLoad($mp)['v'];$s=$m['source']['commit_sha']??'';prodReqEq($m['release']['id']??null,'production-'.substr($s,0,12),'release');prodReqEq($m['runtime']['required_runtime_class']??null,'production','runtime');prodReqEq($m['runtime']['business_runtime_activation_ready']??null,false,'business_runtime');$ash=$m['artifact']['sha256']??'';if(!hash_equals($ash,hash_file('sha256',$ap)))prodReqFail('artifact');
 $sl=prodReqLoad($sp);$st=$sl['v'];prodReqEq($st['evidence_state']??null,'DEPLOYED_VERIFIED_NOT_SELECTED','staging_state');prodReqEq($st['runtime_class']??null,'durable-staging','staging_runtime');prodReqEq($st['source_commit']??null,$s,'staging_source');foreach(['preflight_passed','previous_active_release_preserved','immutable_release_extracted','public_document_root_verified','external_runtime_configuration_bound','provenance_readback_verified','configuration_read_before_write_verified','configuration_read_after_write_verified','non_mutating_health_attestation_verified','rollback_path_verified']as$f)prodReqEq($st['verification'][$f]??null,true,'staging_'.$f);prodReqEq($st['secrets_embedded']??null,false,'staging_secret');
 $t=prodReqLoad($tp)['v'];prodReqEq($t['target_state']??null,'PRODUCTION_TARGET_CANDIDATE','target');prodReqEq($t['runtime_class']??null,'production','target_runtime');prodReqEq($t['production']??null,true,'target_prod');prodReqEq($t['isolated_environment']??null,true,'isolated');foreach(['durable_database_persistence','durable_session','authorization','transaction_durability','pos_durability','authenticated_configuration_channel','read_before_write','read_after_write','non_mutating_health_attestation','verified_rollback']as$f)prodReqEq($t['capabilities'][$f]??null,true,'cap_'.$f);prodReqEq($t['configuration']['secret_values_embedded']??null,false,'secret');foreach(['ONEQAY_RUNTIME_CLASS','ONEQAY_RUNNING_SOURCE_COMMIT','ONEQAY_RUNNING_ARTIFACT_SHA256','ONEQAY_PRODUCTION_ENVIRONMENT_ID','ONEQAY_PRODUCTION_ATTESTATION_TOKEN']as$f)prodReqEq($t['configuration']['required_binding_presence'][$f]??null,true,'binding_'.$f);
 $env=$t['environment_id']??'';if(!is_string($env)||preg_match('/\A[a-z0-9][a-z0-9-]{2,62}\z/',$env)!==1)prodReqFail('env');$tsha=hash('sha256',prodReqCanonical($t));$ssha=hash('sha256',$sl['raw']);$id='production-deployment-request-'.substr(hash('sha256',implode('|',[$s,$ash,$ssha,$env,$tsha])),0,24);
 return['schema_version'=>1,'request_state'=>'PRODUCTION_DEPLOYMENT_AUTHORITY_REQUEST_PENDING_APPROVAL','request_id'=>$id,'requested_scope'=>'DEPLOY_EXACT_PRODUCTION_ARTIFACT_TO_EXACT_PRODUCTION_TARGET_NOT_ACTIVATE_TRAFFIC','release_id'=>$m['release']['id'],'source_commit'=>$s,'artifact_sha256'=>$ash,'manifest_sha256'=>hash_file('sha256',$mp),'staging_evidence_sha256'=>$ssha,'environment_id'=>$env,'target_descriptor_sha256'=>$tsha,'required_authority'=>['state'=>'NOT_GRANTED','separate_operational_authority_required'=>true,'approval_token_required'=>true,'maximum_lifetime_seconds'=>900],'migration_execution_authorized'=>false,'production_authorized'=>false,'production_traffic_activation_authorized'=>false,'target_selection_authorized'=>false,'producer_dispatch_authorized'=>false,'attribution'=>'Lab | zefry'];
}
function prodReqWrite(string$p,array$v):void{$j=json_encode($v,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR).PHP_EOL;if(file_put_contents($p,$j,LOCK_EX)!==strlen($j))prodReqFail('write');@chmod($p,0600);}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){if($argc!==6)exit(64);try{prodReqWrite($argv[5],prodReqPrepare($argv[1],$argv[2],$argv[3],$argv[4]));fwrite(STDOUT,"production_deployment_authority_request_prepared\n");exit(0);}catch(Throwable$e){fwrite(STDERR,"production_deployment_authority_request_failed:".$e->getMessage()."\n");exit(1);}}
