<?php
declare(strict_types=1);

// Author by Lab | zefry
function prodAuthFail(string$c):never{throw new RuntimeException($c);}
function prodAuthLoad(string$p):array{if(!is_file($p)||is_link($p))prodAuthFail('input');$r=(string)file_get_contents($p);try{$v=json_decode($r,true,64,JSON_THROW_ON_ERROR);}catch(JsonException){prodAuthFail('json');}if(!is_array($v)||array_is_list($v))prodAuthFail('shape');return['v'=>$v,'raw'=>$r];}
function prodAuthEq(mixed$a,mixed$e,string$c):void{if($a!==$e)prodAuthFail($c);}
function prodAuthQualify(string$rp,string$ap):array{$rl=prodAuthLoad($rp);$r=$rl['v'];$al=prodAuthLoad($ap);$a=$al['v'];prodAuthEq($r['request_state']??null,'PRODUCTION_DEPLOYMENT_AUTHORITY_REQUEST_PENDING_APPROVAL','request');prodAuthEq($a['authority_state']??null,'GRANTED_FOR_EXACT_PRODUCTION_DEPLOYMENT_NOT_TRAFFIC_ACTIVATION','state');prodAuthEq($a['request_id']??null,$r['request_id']??null,'request_id');prodAuthEq($a['request_sha256']??null,hash('sha256',$rl['raw']),'request_sha');foreach(['environment_id','target_descriptor_sha256','release_id','artifact_sha256']as$f)prodAuthEq($a[$f]??null,$r[$f]??null,$f);foreach(['deployment_allowed','production_allowed']as$f)prodAuthEq($a[$f]??null,true,$f);foreach(['migration_execution_allowed','production_traffic_activation_allowed','target_selection_allowed','producer_dispatch_allowed']as$f)prodAuthEq($a[$f]??null,false,$f);$from=$a['authorized_at_unix']??0;$to=$a['expires_at_unix']??0;if(!is_int($from)||!is_int($to)||$to<=$from||$to-$from>900||time()<$from||time()>$to)prodAuthFail('lifetime');$token=$a['approval_token']??'';if(!is_string($token)||strlen($token)<32||strlen($token)>256)prodAuthFail('token');return['schema_version'=>1,'binding_state'=>'EXTERNAL_PRODUCTION_DEPLOYMENT_AUTHORITY_QUALIFIED_NOT_EXECUTED','authority_id'=>$a['authority_id'],'authority_sha256'=>hash('sha256',$al['raw']),'approval_token_sha256'=>hash('sha256',$token),'request_id'=>$r['request_id'],'request_sha256'=>hash('sha256',$rl['raw']),'environment_id'=>$r['environment_id'],'target_descriptor_sha256'=>$r['target_descriptor_sha256'],'release_id'=>$r['release_id'],'artifact_sha256'=>$r['artifact_sha256'],'authorized_at_unix'=>$from,'expires_at_unix'=>$to,'deployment_allowed'=>true,'production_allowed'=>true,'migration_execution_allowed'=>false,'production_traffic_activation_allowed'=>false,'target_selection_allowed'=>false,'producer_dispatch_allowed'=>false,'secret_values_embedded'=>false,'attribution'=>'Lab | zefry'];}
function prodAuthWrite(string$p,array$v):void{$j=json_encode($v,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR).PHP_EOL;if(file_put_contents($p,$j,LOCK_EX)!==strlen($j))prodAuthFail('write');@chmod($p,0600);}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){if($argc!==4)exit(64);try{prodAuthWrite($argv[3],prodAuthQualify($argv[1],$argv[2]));fwrite(STDOUT,"production_deployment_authority_qualified\n");exit(0);}catch(Throwable$e){fwrite(STDERR,"production_deployment_authority_failed:".$e->getMessage()."\n");exit(1);}}
