<?php
declare(strict_types=1);

// Author by Lab | zefry
function prodEvFail(string$c):never{throw new RuntimeException($c);}
function prodEvLoad(string$p):array{if(!is_file($p)||is_link($p))prodEvFail('input');try{$v=json_decode((string)file_get_contents($p),true,64,JSON_THROW_ON_ERROR);}catch(JsonException){prodEvFail('json');}if(!is_array($v)||array_is_list($v))prodEvFail('shape');return$v;}
function prodEvEq(mixed$a,mixed$e,string$c):void{if($a!==$e)prodEvFail($c);}
function prodEvQualify(string$pp,string$ep):array{$p=prodEvLoad($pp);$e=prodEvLoad($ep);prodEvEq($p['plan_state']??null,'QUALIFIED_FOR_PRODUCTION_DEPLOYMENT_NOT_EXECUTED_NOT_ACTIVATED','plan');prodEvEq($e['evidence_state']??null,'PRODUCTION_DEPLOYMENT_EVIDENCE_CANDIDATE','candidate');prodEvEq($e['deployment_plan_fingerprint']??null,$p['plan_fingerprint']??null,'fingerprint');prodEvEq($e['environment_id']??null,$p['target']['environment_id']??null,'env');prodEvEq($e['runtime_class']??null,'production','runtime');prodEvEq($e['release_id']??null,$p['artifact']['release_id']??null,'release');prodEvEq($e['source_commit']??null,$p['artifact']['source_commit']??null,'source');prodEvEq($e['artifact_sha256']??null,$p['artifact']['artifact_sha256']??null,'artifact');foreach(['preflight_passed','previous_active_release_preserved','immutable_release_extracted','public_document_root_verified','external_runtime_configuration_bound','provenance_readback_verified','configuration_read_before_write_verified','configuration_read_after_write_verified','non_mutating_health_attestation_verified','rollback_path_verified','candidate_restored_after_rollback_rehearsal']as$f)prodEvEq($e['verification'][$f]??null,true,$f);prodEvEq($e['runtime_readback']['exact_running_source_commit']??null,$p['artifact']['source_commit']??null,'readback_source');prodEvEq($e['runtime_readback']['exact_running_artifact_sha256']??null,$p['artifact']['artifact_sha256']??null,'readback_artifact');prodEvEq($e['runtime_readback']['business_runtime_activation_ready']??null,false,'business_runtime');prodEvEq($e['runtime_readback']['production_traffic_active']??null,false,'traffic');prodEvEq($e['secrets_embedded']??null,false,'secret');return['schema_version'=>1,'evidence_state'=>'PRODUCTION_DEPLOYED_VERIFIED_NOT_ACTIVATED','environment_id'=>$e['environment_id'],'runtime_class'=>'production','release_id'=>$e['release_id'],'source_commit'=>$e['source_commit'],'artifact_sha256'=>$e['artifact_sha256'],'deployment_plan_fingerprint'=>$e['deployment_plan_fingerprint'],'verification'=>$e['verification'],'runtime_readback'=>$e['runtime_readback'],'operational_boundary'=>['migration27_execution'=>'NOT_PERFORMED','permission_provisioning'=>'NONE','feature_activation'=>'INACTIVE','technical_preview_activation'=>'NOT_AUTHORIZED','production_activation'=>'NOT_AUTHORIZED','updater_activation'=>'INACTIVE','target_selection'=>'NOT_PERFORMED','selected_target'=>null,'producer_dispatch'=>'NOT_PERFORMED'],'secrets_embedded'=>false,'attribution'=>'Lab | zefry'];}
function prodEvWrite(string$p,array$v):void{$j=json_encode($v,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR).PHP_EOL;if(file_put_contents($p,$j,LOCK_EX)!==strlen($j))prodEvFail('write');@chmod($p,0600);}
if(PHP_SAPI==='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){if($argc!==4)exit(64);try{prodEvWrite($argv[3],prodEvQualify($argv[1],$argv[2]));fwrite(STDOUT,"production_deployment_evidence_qualified_not_activated\n");exit(0);}catch(Throwable$e){fwrite(STDERR,"production_deployment_evidence_failed:".$e->getMessage()."\n");exit(1);}}
